/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2022-11-10 08:14:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<footer id=\"footer\" class=\"footer\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav class=\"navbar\" role=\"navigation\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-menu navbar-start\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"navbar-link\">회사소개</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"navbar-link\">이용약관</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"navbar-link\">개인정보처리방침</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"navbar-link\">멤버십 프로그램</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"select is-multiple\">\r\n");
      out.write("\t\t\t  <select name=\"sel\">\r\n");
      out.write("\t\t\t    <option value=\"http://www.hyundaihmall.com/\">현대 Mall</option>\r\n");
      out.write("\t\t\t    <option value=\"http://www.thehyundai.com/\">더 현대닷컴</option>\r\n");
      out.write("\t\t\t    <option value=\"https://www.hddfs.com/shop/dm/main.do?ptnrChlCd=00003014\">현대백화점 DUTY FREE</option>\r\n");
      out.write("\t\t\t    <option value=\"http://esuper.ehyundai.com/\">E 수퍼마켓</option>\r\n");
      out.write("\t\t\t    <option value=\"http://www.thehandsome.com/\">더한섬</option>\r\n");
      out.write("\t\t\t    <option value=\"http://mall.hyundailivart.co.kr/\">현대 리바트몰</option>\r\n");
      out.write("\t\t\t    <option value=\"http://www.hyundairentalcare.co.kr/\">현대 렌탈케어</option>\r\n");
      out.write("\t\t\t    <option value=\"http://www.hfashionmall.com/\">H패션몰</option>\r\n");
      out.write("\t\t\t    <option value=\"https://www.h-vrstation.com/main\">현대물산</option>\r\n");
      out.write("\t\t\t    <option value=\"http://www.ehyundai.com\">현대백화점</option>\r\n");
      out.write("\t\t\t    <option value=\"http://www.hyundaihmall.com/\">현대홈쇼핑</option>\r\n");
      out.write("\t\t\t    <option value=\"http://www.hyundaigreenfood.com\">현대그린푸드</option>\r\n");
      out.write("\t\t\t  </select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"ft_left\">\r\n");
      out.write("\t\t\t<h2 class=\"ft_tit\">고객센터</h2>\r\n");
      out.write("\t\t\t<h2 class=\"ft_tel\">1800-0700</h2>\r\n");
      out.write("\t\t\t<p class=\"ft_com\">\r\n");
      out.write("\t\t\t\t평일, 토요일 7:00~18:00<br>\r\n");
      out.write("\t\t\t\t공휴일 7시 ~ 13시 (일요일 휴무)<br>\r\n");
      out.write("\t\t\t\t카카오톡 @그리팅 친구 추가하고 소식과 혜택을 받아보세요.<br><br><br>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<ul class=\"ft_ico_lst\">\r\n");
      out.write("\t\t\t\t<li><a href=\"\" class=\"insta\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\" class=\"utb\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\" class=\"blog\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\" class=\"talk\"></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"ft-right\">\r\n");
      out.write("\t\t\t<h2 class=\"ft_tit\">현대그린푸드</h2>\r\n");
      out.write("\t\t\t<p class=\"ft_com\">\r\n");
      out.write("\t\t\t대표이사 : 박홍진 | 사업장소재지 : 경기도 용인시 수지구 문인로 30(동천동) 현대그린푸드 <br>\r\n");
      out.write("\t\t\t사업자등록번호 : 211-81-08241 [사업자정보확인] | 통신판매신고번호 : 제 2011-용인수지-0268 호<br>\r\n");
      out.write("\t\t\t개인정보보호책임자 : 김해곤 | 개인정보 관리 이메일 : hdgreenfood@hyundaigreenfood.com<br>\r\n");
      out.write("\t\t\t호스팅 서비스 사업자 : (주)현대그린푸드\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p class=\"ft_com\">\r\n");
      out.write("\t\t\t그리팅의 개별 판매자가 등록한 상품(브랜드직송)에 대한 광고, 상품주문, 배송, 환불의 의무와 책임은\r\n");
      out.write("\t\t\t각 판매자가 부담하고, 그리팅은 통신판매 중개자로서의 의무와 책임을 다합니다.\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\" style=\"clear:both; text-align:center;\">\r\n");
      out.write("\t\t<p style=\"font-weight:bold;\">Copyright © 2020 HYUNDAI GREEN FOOD. All Rights Reserved.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
